name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
env:
  MY_GLOBAL_VAR: 'This is a global variable'
jobs:
  my-first-job:
    env:
      MY_LOCAL_VAR: ${{ 34 }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install -g bats
      - run: bats -v

      - name: PWD
        run: |
          pwd
          cd .github/actions/hello-bash
          ls -la
          ls -la /home/runner/work/design_patterns/design_patterns/.github/actions/hello-bash

      - name: Run Hello World Action
        uses: ./.github/actions/hello-bash
        with:
          who-to-greet: 'Antonio'

      - name: Show global var
        run: echo $MY_GLOBAL_VAR

      - name: Show local var
        run: echo $MY_LOCAL_VAR

      - name: Show expression value
        run: echo ${{ (33 + 1) }}

